In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Iris.csv")
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [4]:
data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
data.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [6]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [7]:
data.duplicated().sum()

0

In [8]:
data.SepalLengthCm.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145     True
146     True
147     True
148     True
149     True
Name: SepalLengthCm, Length: 150, dtype: bool

In [9]:
data.SepalLengthCm.duplicated().sum()

115

In [10]:
data[data.SepalLengthCm.duplicated()]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [11]:
data[data.SepalLengthCm.duplicated()].sum()

Id                                                            9484
SepalLengthCm                                                666.1
SepalWidthCm                                                 345.9
PetalLengthCm                                                440.3
PetalWidthCm                                                 143.5
Species          Iris-setosaIris-setosaIris-setosaIris-setosaIr...
dtype: object

In [12]:
data.drop_duplicates(subset=['SepalLengthCm'])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
27,28,5.2,3.5,1.5,0.2,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
48,49,5.3,3.7,1.5,0.2,Iris-setosa
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
58,59,6.6,2.9,4.6,1.3,Iris-versicolor
61,62,5.9,3.0,4.2,1.5,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
65,66,6.7,3.1,4.4,1.4,Iris-versicolor
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
76,77,6.8,2.8,4.8,1.4,Iris-versicolor
102,103,7.1,3.0,5.9,2.1,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica

In [13]:
data.SepalWidthCm.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145     True
146     True
147     True
148     True
149     True
Name: SepalWidthCm, Length: 150, dtype: bool

In [14]:
data.SepalWidthCm.duplicated().sum()

127

In [15]:
data[data.SepalWidthCm.duplicated()]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
7,8,5.0,3.4,1.5,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [16]:
data[data.SepalWidthCm.duplicated()].sum()

Id                                                           10647
SepalLengthCm                                                756.0
SepalWidthCm                                                 384.5
PetalLengthCm                                                513.8
PetalWidthCm                                                 167.7
Species          Iris-setosaIris-setosaIris-setosaIris-setosaIr...
dtype: object

In [17]:
data.drop_duplicates(subset=['SepalWidthCm'])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor
69,70,5.6,2.5,3.9,1.1,Iris-versicolor
79,80,5.7,2.6,3.5,1.0,Iris-versicolor

In [18]:
data.drop_duplicates(subset=['SepalLengthCm', 'SepalWidthCm'])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica

In [31]:
data.drop_duplicates(subset=['SepalLengthCm', 'SepalWidthCm'], keep = 'last')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,2,4.9,3.0,1.4,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [19]:
data.PetalLengthCm.duplicated()

0      False
1       True
2      False
3      False
4       True
       ...
145    False
146     True
147     True
148     True
149     True
Name: PetalLengthCm, Length: 150, dtype: bool

In [20]:
data.PetalLengthCm.duplicated().sum()

107

In [21]:
data[data.PetalLengthCm.duplicated()]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,2,4.9,3.0,1.4,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
144,145,6.7,3.3,5.7,2.5,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [27]:
data[data.PetalLengthCm.duplicated()].sum()

Id                                                            8209
SepalLengthCm                                                614.6
SepalWidthCm                                                 327.6
PetalLengthCm                                                382.3
PetalWidthCm                                                 120.3
Species          Iris-setosaIris-setosaIris-setosaIris-setosaIr...
dtype: object

In [29]:
data.drop_duplicates(subset=['PetalLengthCm'])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
22,23,4.6,3.6,1.0,0.2,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
61,62,5.9,3.0,4.2,1.5,Iris-versicolor
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
65,66,6.7,3.1,4.4,1.4,Iris-versicolor
67,68,5.8,2.7,4.1,1.0,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
74,75,6.4,2.9,4.3,1.3,Iris-versicolor
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
80,81,5.5,2.4,3.8,1.1,Iris-versicolor
81,82,5.5,2.4,3.7,1.0,Iris-versicolor
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
98,99,5.1,2.5,3.0,1.1,Iris-versicolor
100,101,6.3,3.3,6.0,2.5,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica

In [24]:
data.PetalWidthCm.duplicated()

0      False
1       True
2       True
3       True
4       True
       ...
145     True
146     True
147     True
148     True
149     True
Name: PetalWidthCm, Length: 150, dtype: bool

In [25]:
data.PetalWidthCm.duplicated().sum()

128

In [26]:
data[data.PetalWidthCm.duplicated()]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [28]:
data[data.PetalWidthCm.duplicated()].sum()

Id                                                            9915
SepalLengthCm                                                747.6
SepalWidthCm                                                 390.3
PetalLengthCm                                                476.6
PetalWidthCm                                                 149.7
Species          Iris-setosaIris-setosaIris-setosaIris-setosaIr...
dtype: object

In [30]:
data.drop_duplicates(subset=['PetalWidthCm'])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
43,44,5.0,3.5,1.6,0.6,Iris-setosa
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
69,70,5.6,2.5,3.9,1.1,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
73,74,6.1,2.8,4.7,1.2,Iris-versicolor
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica

In [22]:
data.drop_duplicates(subset=['PetalLengthCm', 'PetalWidthCm'])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [23]:
data.drop_duplicates(subset=['PetalLengthCm', 'PetalWidthCm'], keep = 'last')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
5,6,5.4,3.9,1.7,0.4,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
16,17,5.4,3.9,1.3,0.4,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica